Minor Universe Fixes (#330)
Summary:
* one of the things I did in my version of md_extract was supress
a ton of Ruby warnings, adding that to the upstream version as well
* Fix a bug in copy_upstream_cookbooks that pulls that script from
the wrong path

Signed-off-by: Phil Dibowitz <phil@ipom.com>

Pull Request resolved: https://github.com/facebook/chef-cookbooks/pull/330

Differential Revision: D78914288

fbshipit-source-id: d99ade741730c5706c3f875eabe8bcaae4e2102c

diff --git a/scripts/copy_upstream_cookbooks b/scripts/copy_upstream_cookbooks
--- a/scripts/copy_upstream_cookbooks
+++ b/scripts/copy_upstream_cookbooks
@@ -33,6 +33,11 @@ debug() {
     echo "DEBUG: $*" >&2
 }
 
+die() {
+    echo "ERROR: $*" >&2
+    exit 1
+}
+
 find_deps() {
     dir="$1"
     deps=()
@@ -41,7 +46,7 @@ find_deps() {
     # and add any we don't have to deps
     for file in "$dir"/cookbooks/*/metadata.rb; do
         # shellcheck disable=SC2207
-        if ! tdeps=($("$dir/scripts/chef_md_extract.rb" 'depends' "$file"));
+        if ! tdeps=($("chef-cookbooks/scripts/chef_md_extract.rb" 'depends' "$file"));
  then
             die "Failed to parse deps from $file"
         fi
