chef: refactor opensource scripts
Summary: Generalize and refactor for consistency

Reviewed By: joshuamiller01

Differential Revision: D17416056

fbshipit-source-id: b6768f20a39221ee0fa3bdf76c6c9e173e1eaac8

diff --git a/scripts/run_chefspec b/scripts/run_chefspec
--- a/scripts/run_chefspec
+++ b/scripts/run_chefspec
@@ -21,7 +21,17 @@ set -eu
 
 COLOR='--color'
 TEST=''
-PATH=/opt/chefdk/embedded/bin:$PATH
+
+if bundle exec rspec --version > /dev/null 2>&1; then
+  RSPEC='bundle exec rspec'
+elif [ -x /opt/chefdk/embedded/bin/rspec ]; then
+  RSPEC='/opt/chefdk/embedded/bin/rspec'
+elif [ -x /opt/chef/embedded/bin/rspec ]; then
+  RSPEC='/opt/chef/embedded/bin/rspec'
+else
+  echo 'Cannot find rspec!'
+  exit 1
+fi
 
 while getopts ":e:c" opt; do
   case $opt in
@@ -51,10 +61,10 @@ done
 
 if [ -z "$TEST" ]; then
   # shellcheck disable=SC2086
-  /opt/chefdk/embedded/bin/rspec $COLOR --format=d $newarg
+  $RSPEC $COLOR --format=d $newarg
 else
   # shellcheck disable=SC2086
-  /opt/chefdk/embedded/bin/rspec -e "$TEST" $COLOR --format=d $newarg
+  $RSPEC -e "$TEST" $COLOR --format=d $newarg
 fi
 RET=$?
 
diff --git a/scripts/run_foodcritic b/scripts/run_foodcritic
--- a/scripts/run_foodcritic
+++ b/scripts/run_foodcritic
@@ -1,4 +1,23 @@
-#!/bin/bash
+#!/bin/sh
+#
+# vim: syntax=ruby:expandtab:shiftwidth=2:softtabstop=2:tabstop=2
+#
+# Copyright (c) 2016-present, Facebook, Inc.
+# All rights reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+# http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+set -eu
 
 # excluded rules
 # FC014 - long ruby blocks
@@ -12,5 +31,19 @@
 # FC094 - this is wrong advice before 13
 # FC113 - will fix this as part of Chef 13 migration
 excluded_rules='FC014 FC017 FC024 FC059 FC064 FC066 FC071 FC085 FC094 FC113'
-exclude_flags=$(for r in $excluded_rules; do echo -t ~$r; done)
-exec bundle exec foodcritic -f any $exclude_flags cookbooks
+# shellcheck disable=SC2039
+exclude_flags=$(for r in $excluded_rules; do echo "-t ~$r"; done)
+
+if bundle exec foodcritic --version > /dev/null 2>&1; then
+  FOODCRITIC='bundle exec foodcritic'
+elif [ -x /opt/chefdk/embedded/bin/foodcritic ]; then
+  FOODCRITIC='/opt/chefdk/embedded/bin/foodcritic'
+elif [ -x /opt/chef/embedded/bin/foodcritic ]; then
+  FOODCRITIC='/opt/chef/embedded/bin/foodcritic'
+else
+  echo 'Cannot find foodcritic!'
+  exit 1
+fi
+
+# shellcheck disable=SC2086
+exec $FOODCRITIC -f any $exclude_flags cookbooks
diff --git a/scripts/run_rubocop b/scripts/run_rubocop
--- a/scripts/run_rubocop
+++ b/scripts/run_rubocop
@@ -19,27 +19,29 @@
 
 set -eu
 
-if [ -z "$SKEY" ]; then
-  SKEY='../supermarket.pem'
-fi
-if [ -z "$SUSER" ]; then
-  SUSER='phild'
-fi
-if [ -z "$TRAVIS_RUBY_VERSION" ]; then
-  BUNDLE='bundle'
+if bundle exec rubocop --version > /dev/null 2>&1; then
+  RUBOCOP='bundle exec rubocop'
+elif [ -x /opt/chefdk/embedded/bin/rubocop ]; then
+  RUBOCOP='/opt/chefdk/embedded/bin/rubocop'
+elif [ -x /opt/chef/embedded/bin/rubocop ]; then
+  RUBOCOP='/opt/chef/embedded/bin/rubocop'
 else
-  BUNDLE="rvm $TRAVIS_RUBY_VERSION do bundle"
+  echo 'Cannot find rubocop!'
+  exit 1
 fi
 
-COMMON_OPTS="-m https://supermarket.chef.io -k $SKEY -u $SUSER"
+if [ "$#" -eq 0 ]; then
+  config='.rubocop.yml'
+elif [ "$#" -eq 1 ]; then
+  config="$1"
+else
+  echo "Usage: $0 [config]"
+  exit 1
+fi
 
-$BUNDLE install
-cd cookbooks
-for i in *; do
-  echo "Unpublishing $i"
-  # shellcheck disable=SC2086
-  $BUNDLE exec knife supermarket unshare "$i" $COMMON_OPTS -y
-  echo "Publishing $i"
-  # shellcheck disable=SC2086
-  $BUNDLE exec knife supermarket share "$i" Other -o . $COMMON_OPTS
-done
+if [ ! -r "$config" ]; then
+  echo "Cannot read rubocop config: $config"
+  exit 1
+fi
+
+exec $RUBOCOP --display-cop-names -c "$config"
